apiVersion: v1
kind: PersistentVolume
metadata:
  name: foundry-data-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/foundry_data"
